// Maps nav icon-name strings (from lib/rbac) to lucide components.
import {
  LayoutDashboard,
  Truck,
  LayoutGrid,
  IdCard,
  Container,
  Building2,
  PackageOpen,
  Warehouse,
  FileText,
  Receipt,
  Star,
  BarChart3,
  Network,
  Users,
  CreditCard,
  Settings,
  Building,
  BadgeDollarSign,
  Megaphone,
  ShieldCheck,
  Activity,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  LayoutDashboard,
  Truck,
  LayoutGrid,
  IdCard,
  Container,
  Building2,
  PackageOpen,
  Warehouse,
  FileText,
  Receipt,
  Star,
  BarChart3,
  Network,
  Users,
  CreditCard,
  Settings,
  Building,
  BadgeDollarSign,
  Megaphone,
  ShieldCheck,
  Activity,
};
